# Generated by Django 4.1.7 on 2023-03-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "resetpasswordlog",
            "0002_resetpasswordlog_expire_at_resetpasswordlog_used_at",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordlog",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
