# Generated by Django 4.1.7 on 2023-03-09 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_telefone_userregistrationlog_useracceslog_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useracceslog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userregistrationlog",
            name="added_by",
        ),
        migrations.RemoveField(
            model_name="userregistrationlog",
            name="new_user",
        ),
        migrations.DeleteModel(
            name="PasswordResetLog",
        ),
        migrations.DeleteModel(
            name="UserAccesLog",
        ),
        migrations.DeleteModel(
            name="UserRegistrationLog",
        ),
    ]
