# Generated by Django 4.1.7 on 2023-03-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_telefone'),
        ('users', '0003_remove_useracceslog_user_and_more'),
    ]

    operations = [
    ]
