# Generated by Django 4.1.7 on 2023-03-15 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_historicaluser_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="telefone",
        ),
    ]
