# Generated by Django 4.1.7 on 2023-03-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_historicaluser_history_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="history_type",
            field=models.CharField(
                choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                max_length=1,
            ),
        ),
    ]
