# Generated by Django 4.1.7 on 2023-03-15 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_historicaluser_history_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalUser",
        ),
    ]
