# Generated by Django 4.1.7 on 2023-03-17 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_userregistrationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregistrationlog",
            name="created_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="register",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
