# Generated by Django 4.1.7 on 2023-03-09 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accesslog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccesslog",
            name="ip_address",
        ),
    ]
