# Generated by Django 4.1.7 on 2023-03-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesslog', '0003_useraccesslog_ip_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistrationLog',
        ),
    ]
