# Generated by Django 4.1.7 on 2023-03-20 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accesslog", "0004_delete_userregistrationlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetLog",
        ),
    ]
